[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "https://shop.backyardgolf.io/*"
  to = "/shop/:splat"
  status = 200
  force = true